spring:
  datasource:
    url: jdbc:h2:mem:testdb          # In-Memory DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none                # oder update, je nach Option
  sql:
    init:
      mode: always                  # Daten aus data.sql laden
server:
  port: 8081